# Generated by Django 4.2 on 2023-05-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилие')),
                ('midlle', models.CharField(max_length=255, verbose_name='Отчесвтво')),
                ('phone', models.CharField(max_length=20, verbose_name='Мобильный номер')),
                ('card', models.CharField(max_length=20, verbose_name='Номер карты')),
                ('products', models.ManyToManyField(to='shop.product')),
            ],
        ),
    ]
