# Generated by Django 4.2 on 2023-05-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='midlle',
            field=models.CharField(max_length=255, null=True, verbose_name='Отчесвтво'),
        ),
    ]
